### ISSUE TITLE
Green background after red

### ISSUE THREAD

**Issue by OskarKlintrot** [OskarKlintrot/1dv411-project#113]
There is a bug that if you try to save the last permutation again then it becomes red, so far so good. If you after that try to save another permutation that also have been previously saved then the background of the last saved becomes green and stays green.
![image](https://cloud.githubusercontent.com/assets/6783879/13635070/be5396e0-e5f9-11e5-8e79-cfc077665bbb.png)

**Comment by lw222gu** [comment]
Fixed!
