### ISSUE TITLE
Viewport for iPad portrait mode

### ISSUE THREAD

**Issue by dv222bk** [OskarKlintrot/1dv411-project#134]
According to my Chrome iPad preview, the viewport set to iPads portrait mode does not work properly.

**Comment by OskarKlintrot** [comment]
Just adding some screenshots to illustrate...

# Startview

![image](https://cloud.githubusercontent.com/assets/6783879/13710788/7cc38956-e7bb-11e5-8522-ad6bb1eb3a13.png)

# Gameview

![image](https://cloud.githubusercontent.com/assets/6783879/13710811/910321e2-e7bb-11e5-9042-9e292da0925b.png)

# Resultview

![image](https://cloud.githubusercontent.com/assets/6783879/13710820/97237b08-e7bb-11e5-9e24-e992d70a012f.png)

**Comment by OskarKlintrot** [comment]
Wont fix since we are going to disable portrait mode in #140.
