### ISSUE TITLE
Height will not update on portrait to landscape mode change

### ISSUE THREAD

**Issue by johnnypesola** [OskarKlintrot/1dv411-project#136]
When the app is loaded in portrait mode, and then later switched to landscape mode the height is not updated, causing some of the content to not be rendered. [Example here](https://youtu.be/7JxJsPQbZSA?t=43)

If the app is loaded in landscape mode and then changed to portrait mode the sofa will float in mid-air and the view will be scrollable. [Example here](https://youtu.be/7JxJsPQbZSA?t=115)

**Comment by OskarKlintrot** [comment]
Wont fix since we are going to disable portrait mode in #140.
