### ISSUE TITLE
Resultview: Number of perm. is not responsive

### ISSUE THREAD

**Issue by dv222bk** [OskarKlintrot/1dv411-project#139]
Cannot be seen on smaller devices in portrait mode

![ss 2016-03-14 at 10 18 45](https://cloud.githubusercontent.com/assets/8626399/13739969/7c5f16b4-e9ce-11e5-9dd4-f3dc9a1086d5.png)

**Comment by OskarKlintrot** [comment]
Wont fix since we are going to disable portrait mode in #140.
