### ISSUE TITLE
Blurred background is not working when using the back-button

### ISSUE THREAD

**Issue by OskarKlintrot** [OskarKlintrot/1dv411-project#82]
Blurred background is not working when using the back-button in the browser.

**Comment by johnnypesola** [comment]
Now fixed
[game view](https://github.com/OskarKlintrot/1dv411-project/blob/dev/src/app/components/gameView/index.jsx#L21-L22)
[result view](https://github.com/OskarKlintrot/1dv411-project/blob/dev/src/app/components/resultView/index.jsx#L13-L14)
[start view](https://github.com/OskarKlintrot/1dv411-project/blob/dev/src/app/components/startView/index.jsx#L26-L27)
