### ISSUE TITLE
Saved permutation scroll is not working

### ISSUE THREAD

**Issue by OskarKlintrot** [OskarKlintrot/1dv411-project#98]
When trying to save an already saved permutation it's not scrolled to the already saved permutation.

**Comment by lw222gu** [comment]
Fixat! Nu scrollar den till redan sparad permutation, och om scrollpositionen inte är högst upp när en ny permutation sparas så scrollar den upp till den nya permutationen.

**Comment by OskarKlintrot** [comment]
What's that language..? :stuck_out_tongue_winking_eye:
